### ISSUE TITLE
Todo from May 8

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/seesaw#1]
- [ ] try removing 2021 from synoptic [@jdunic]
- [ ] try removing 2021 inside hbll_grid  [@jdunic]
- [ ] fix the N / S for inside HBLL and outside HBLL [@jdunic]
- [ ] try to get hbll outside converging with rw timevarying: zero centered, fix SD, AR1 fields, strong PC prior on the fields? [@seananderson]
